### ISSUE TITLE
when *ring* is not disabled

### ISSUE THREAD

**Issue by dahn-d** [springweblobby/swl-website#37] opened 2015-09-29 11:49 UTC
if **zkl** and **weblobby** is running and i am in some room in specs, then weblobby ringing is not disabled when the room game starts. open both lobbies and test it out typing something in global chat while ingame.
btw, dont ask why im using both lobbies together :p

**Comment by Anarchid** [comment] 2015-09-29 14:28
My guess: weblobby **can't** know that you're running Spring via ZKL. 

This looks like a wontfix.

**Comment by db81** [comment] 2015-09-29 14:53
It rings you if you're mentioned in in a channel outside of the battleroom or private messaged even when Spring is running. This is by design.

Same for when you're mentioned in the battleroom and the battle is running but you aren't watching it (i.e. spring isn't running).

If this is about the ring being enabled after Spring was launched by ZKL, then what @Anarchid said.

**Comment by dahn-d** [comment] 2015-09-29 21:08
oh ye. i agree.

**Closed** 2015-09-30 05:53 UTC
